version: "3.8"

# the volumes part
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/psadeghi/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/psadeghi/data/wordpress
      o : bind
      type : none


# the networks part
networks:
  inception:
    name: inception


# the services part
services:
#mariadb
  mariadb:
#    image: mariadb:psadeghi
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always
#nginx
  nginx:
#    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
#    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - 9000
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always
